### ISSUE TITLE
demo content

### ISSUE THREAD

**Issue by richardeth** [neilgee/genesischild-mobile-first#14]
I am trying to make a test site exactly the same as your example located at: http://themes.wpbeaches.com/genesischild-mobile-first/ but I was wondering if there is an import file available to make the site exactly as your demo?

Greetings Richard

**Comment by neilgee** [comment]
Hi Richard - actually it doesn't I used the woocommerce data xml dummy content and some made up widget/plugin settings - but this is something I'd like to do when I have some time - it's on the list!

**Comment by richardeth** [comment]
Would be great,

I already found my problem. The Featured Custom Post Type Widget For Genesis doesnt seem to work automatic so I installed the plugin and after that I could make my test theme more like yours 👍 

I've learned a lot from your example, thanks a lot for sharing it!

**Comment by neilgee** [comment]
Ok great, I'll have to check why the default installed Custom Post Type widget didn't work, I do use this starter theme as my regular base.

**Comment by neilgee** [comment]
Seems I didn't register the Featured Custom Post Type widget - now registered!

**Comment by richardeth** [comment]
Thx, I was having a problem with the right way to do that, again thx for showing me how!
