### ISSUE TITLE
Issue in Safari with Navigation Rearrange

### ISSUE THREAD

**Issue by dmvieira74** [neilgee/genesischild-mobile-first#15]
Hello Neil,

I think I have discovered an issue in Safari on Mac OS X when you uncomment the "Rearrange Header Nav" actions on line lines 98 and 99 in functions.php.
This issue happens when responsive-menu.php is enabled and lines 98 & 99 are commented out so the navigation is under the logo instead of on the right hand side of it.

When the mobile menu kicks in and you click on MENU the navigation jumps to  the top of the screen and the first nav item gets cut off. If you invoke any dropdowns the content moves up and gets even more cut off.

Other browsers seem to handle it just fine.

I am using Safari Version 10.1.1 (12603.2.4) on Mac OSX Version 10.2.5.

Please let me know if you need any more information.

Thanks!
Dennis

**Comment by neilgee** [comment]
Thanks for letting me know Dennis - think I have a flexbox issue, will investigate.

**Comment by neilgee** [comment]
Did a fix for this in `style.css` in the Sticky Footer area...
```
--------------------------------------------- */
/* Sticky Footer
 * https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css
 */

.site-container {
	display: -ms-flexbox;
	display:-webkit-flex;
	display:-webkit-box;
	display:flex;
	-ms-flex-direction:column;
	-webkit-flex-direction:column;
	-webkit-box-orient:vertical;
	-webkit-box-direction:normal;
	flex-direction:column;
	min-height:100vh;
}
```
diff is the `min-height:100vh;`

a39f515bc9a6c33b9b7a790f050ca1df4be9aeef

And the latest has the newer Genesis responsive menu added.
